keys:
  - &clementine age18u6w0slrgtarcf5gvc30te66ctun79ltlupcj955vayh062wrs9qjqhdas
  - &angeles age1n94j0rpzcq244edtmvrcyjqhsl3me5y9meng4yc3jurqwfdugd5qc9nh58
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
      - age:
        - *clementine
        - *angeles
